jobs:
  - job: Build
    steps:
      - task: PowerShell@2
        enabled: 'true'
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: 'npm ci'
          workingDirectory: tests/ # update accordingly

      - task: AzureCLI@2
        displayName: Run Playwright Test  
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          # PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN) # Not recommended, use Microsoft Entra ID authentication. 

        inputs:
          azureSubscription: My_Service_Connection # Service connection used to authenticate this pipeline with Azure to use the service
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            npx playwright test --config=playwright.service.config.js --workers=5
          addSpnToEnvironment: true
          workingDirectory: path/to/playwright/folder # update accordingly

      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report
        inputs:
          targetPath: path/to/playwright/folder/playwright-report/ # update accordingly
          artifact: 'Playwright tests'
          publishLocation: 'pipeline'